### ISSUE TITLE
We need provide customers another option to use existing chef vault for higher security

### ISSUE THREAD

**Issue by Umleitungen** [ibmbpm/Workflow_Chef#1]
In each properties file, we add two new properties to provide our customers the possibility to use existing chef vault created ahead of time by themselves with higher security for BAW password encryption.

Keep either or both empty to disable using existing chef vault, but you need fill in the following passwords vaules required in this properties file.
Fill in all these properties under this Existing Chef Vault section to enable using existing chef vault on the Chef Server when a higher security is required.

If enabled, you can keep all the following passwords required below as empty, however you must creating a chef vault (see Chef Vault documentaion: https://docs.chef.io/chef_vault.html) with these passwords on the Chef Server manually ahead of time.
You can find the templates with all passwords required for creating the chef vault as follows,
Fresh Install: <Workflow_Chef_ROOT>/templates/chef_vault_json/workflow_secrets_fresh_install.json.
Applyifix or Upgrade: <Workflow_Chef_ROOT>/templates/chef_vault_json/workflow_secrets_applyifix_upgrade.json.
Replace the json vaule with your own passwords, then use this knife command below to create a chef vault on Chef Server:
knife vault create <workflow_chef_vault_name> <workflow_chef_vault_item> --json --mode client

**Comment by bjwhtao** [comment]
Solved by release v1.0.1, commit ID: 1b7323c76e25e8268822f386accf3489de254df8
